version: '3.4'

services:
  autoencoders:
    image: autoencoders
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: data
        target: /app/data
    ports:
      - target: "6006"
        published: "6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
